services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: erp_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"   # لو البورت محجوز عندك غيّره مثلا "5433:5432" وغيّر DB_PORT في .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d erp_system"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    command: >
      bash -lc "
        until pg_isready -h db -p 5432 -U postgres -d erp_system; do
          echo 'waiting for postgres...'; sleep 1;
        done &&
        python manage.py migrate --noinput &&
        daphne -b 0.0.0.0 -p 8000 erp_system.asgi:application
      "
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=erp_system.settings
      - TZ=Asia/Dubai

  notifier:
    build:
      context: ./backend
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=erp_system.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Dubai
    command: >
      bash -lc "
        while true; do
          echo '[notifier] running notify_expiring...';
          python manage.py notify_expiring;
          sleep 900;
        done
      "

  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_started
    command: npm run dev

volumes:
  postgres_data:
