# render.yaml
services:
  # ===== Backend (Django ASGI via Daphne) =====
  - type: web
    name: erb-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      # Core
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: TIME_ZONE
        value: "Asia/Dubai"

      # Hosts/CORS/CSRF
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1"   # بعد الإنشاء: أضِف دومين Render هنا
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://erb-frontend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://erb-frontend.onrender.com"

      # Database (Render سيملأها تلقائيًا)
      - key: DATABASE_URL
        fromDatabase:
          name: erb-postgres
          property: connectionString

      # Redis (Channels)
      - key: REDIS_URL
        fromService:
          type: redis
          name: erb-redis
          property: connectionString

      # اختياري
      - key: SITE_BASE_URL
        value: "https://erb-backend.onrender.com"

    healthCheckPath: "/admin/login"

  # ===== Worker (notifier loop) =====
  - type: worker
    name: erb-notifier
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    startCommand: >
      bash -lc "while true; do
        echo '[notifier] running notify_expiring...';
        python manage.py notify_expiring;
        sleep 900;
      done"
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: TIME_ZONE
        value: "Asia/Dubai"
      - key: DATABASE_URL
        fromDatabase:
          name: erb-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: erb-redis
          property: connectionString

  # ===== Redis (Managed) =====
  - type: redis
    name: erb-redis
    plan: free

  # ===== Frontend (Vite Static Site) =====
  - type: web
    name: erb-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"     # ← هنا التعديل بدل publishPath
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: "https://erb-backend.onrender.com"   # حدّثه بعد معرفة دومين الباك إند

databases:
  - name: erb-postgres
    plan: free
