# Generated by Django 5.1.6 on 2025-08-18 11:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_project_number', models.IntegerField(unique=True, verbose_name='Bank Project Number')),
                ('project_code', models.CharField(max_length=100, unique=True, verbose_name='Project Code')),
                ('main_contractor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Contractor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('report_as_of', models.DateField(blank=True, null=True, verbose_name='Report As-Of Date')),
                ('engineering_auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('engineering_audit_date', models.DateField(blank=True, null=True)),
                ('accounting_auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('accounting_audit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('first_funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('second_funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('start_order_date', models.DateField(blank=True, null=True)),
                ('contract_duration_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_time_extension_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consultant_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bank_total_financing_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bank_completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bank_consultant_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('owner_completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('owner_consultant_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consultant', models.ForeignKey(limit_choices_to={'customer_type': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consulted_projects', to='customers.customer', verbose_name='Consultant')),
                ('owner', models.ForeignKey(limit_choices_to={'customer_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='customers.customer', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-bank_project_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('CLIENT', 'Client Payment'), ('BANK', 'Bank Payment'), ('OTHER', 'Other')], default='CLIENT', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_number', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('-999999999999.99'))])),
                ('consultant_fee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_orders', to='projects.project')),
            ],
            options={
                'ordering': ['date', 'id'],
                'unique_together': {('project', 'variation_number')},
            },
        ),
    ]
