# Generated by Django 4.2.23 on 2025-09-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='secondary', help_text='Bootstrap color name: primary, success, warning, danger…', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('owner_email', models.EmailField(blank=True, help_text='Recipient for expiry alerts (optional).', max_length=254)),
                ('expires_on', models.DateField()),
                ('alert_window_days', models.PositiveIntegerField(default=7, help_text='Send an alert this many days before expiry.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_notified_on', models.DateField(blank=True, null=True)),
                ('last_notified_for_expires_on', models.DateField(blank=True, null=True)),
                ('last_notified_for_offset', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.category')),
            ],
            options={
                'ordering': ['expires_on', 'title'],
            },
        ),
    ]
